#web服务访问端口
server:
  port: 8080

#langchain4j配置
langchain4j:
  #openai
  open-ai:
    chat-model:
      #langchain4j模型
      #base-url: http://langchain4j.dev/demo/openai/v1
      #api-key: demo
      #model-name: gpt-4o-mini

      #deepseek模型
      #base-url: https://api.deepseek.com
      #api-key: ${DEEP_SEEK_API_KEY}
      #model-name: deepseek-chat

      #deepseek模型(阿里云百炼平台)
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${DASH_SCOPE_API_KEY}
      model-name: deepseek-v3

      #应用程序发送给大模型的请求日志和响应日志
      log-requests: true
      log-responses: true
  #ollama
  ollama:
    chat-model:
      #ollama
      base-url: http://localhost:11434
      model-name: deepseek-r1:1.5b
      temperature: 0.8
      timeout: PT60S
  #阿里百炼
  community:
    dashscope:
      chat-model:
        api-key: ${DASH_SCOPE_API_KEY}
        model-name: qwen-max

#系统日志级别
logging:
  level:
    root: debug